version: '3'
services:
  app:
    build: .
    volumes:
      - .:/websocket
    ports:
      - 8000:8000

    image: app:websocket
    container_name: websocket_container
    command: python3 manage.py runserver 0.0.0.0:8000